apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  namespace: 20227-rosa
  name: webapp-20227-rolebinding
subjects:
- kind: ServiceAccount
  name: webapp-20227-sa
roleRef:
  kind: Role
  name: webapp-20227-role
  apiGroup: rbac.authorization.k8s.io